services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  waha:
    image: devlikeapro/waha
    ports:
      - "3001:300"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
