# Generated by Django 5.1.7 on 2025-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='schedule_type',
            field=models.CharField(choices=[('DA', 'Daily'), ('WE', 'Weekly'), ('MO', 'Monthly'), ('EX', 'Exact')], default='DA', max_length=2),
        ),
    ]
