# Generated by Django 5.1.7 on 2025-03-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
